def get_number_symbol_slice(content: str) -> int:
    return content.find('<url>', len(content) // 2)


def add_and_replace_str(content: str, nubmer_sitemap: str) -> str:
    string_add = content[content.rfind('<sitemap>')-2:content.rfind('</sitemap>') + 10]
    content = content + string_add
    return content.replace('sitemap3.xml', f'sitemap{nubmer_sitemap}.xml')


if __name__ == "__main__":
    string_1 = '<?xml version="1.0" encoding="utf-8"?><!--Generated by Screaming Frog SEO Spider 12.6-->'
    string_2 = '\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'

    for i in range(4):
        print(i)
        with open(f'Sitemap/sitemap{i}.xml', 'r') as file:
            content = file.read()
            number_slice_symbol = get_number_symbol_slice(content)
            sitemap_1 = content[:number_slice_symbol - 3] + '\n</urlset>'
            sitemap_2 = string_1 + string_2 + content[number_slice_symbol - 3:]
            sitemap = open(f'SplitSitemap/sitemap{i}_1.xml', 'w')
            sitemap.write(sitemap_1)
            sitemap.close()
            sitemap = open(f'SplitSitemap/sitemap{i}_2.xml', 'w')
            sitemap.write(sitemap_2)
            sitemap.close()
    with open('Sitemap/sitemapindex.xml', 'r') as file:
        content = file.read()
        content = content[:-15]
        content = content.replace('sitemap.xml', 'sitemap0_1.xml')
        content = content.replace('sitemap1.xml', 'sitemap0_2.xml')
        content = content.replace('sitemap2.xml', 'sitemap1_1.xml')
        content = content.replace('sitemap3.xml', 'sitemap1_2.xml')
        content = add_and_replace_str(content, '2_1')
        content = '\n' + add_and_replace_str(content, '2_2')
        content = '\n' + add_and_replace_str(content, '3_1')
        content = '\n' + add_and_replace_str(content, '3_2') + '\n</sitemapindex>'
        f = open('SplitSitemap/sitemapindex.xml', 'w')
        f.write(content.strip('\n'))
        f.close()
